<?php if ($block->isActiveCsvPricing()) :?>
    <?php if ($block->_product->getApplyCsvType() == 'dimensional') : ?>
        <?php $data = $block->jsonEncodeandDecode(); ?>
        <script type="text/x-magento-init">
        {
                "#product_addtocart_form": {
                    "MageArray_Customprice/js/custompriceonedimensional": {
                        "optionConfig": <?= /* @escapeNotVerified */ $data?>,
                        "controlContainer": ".field",
                        "priceHolderSelector": "[data-role=priceBox]"
                    }
                }
            }
        </script>
    <?php elseif ($block->_product->getApplyCsvType() == 'multiple') : ?>
        <?php $data=$block->jsonEncodeandDecode();?>
        <script type="text/x-magento-init">
        {
                "#product_addtocart_form": {
                    "MageArray_Customprice/js/custompricepro": {
                        "optionConfig": <?= /* @escapeNotVerified */ $data?>,
                        "controlContainer": ".field",
                        "priceHolderSelector": "[data-role=priceBox]"
                    }
                }
            }
        </script>
    <?php else : ?>
        <?php $data=$block->jsonEncodeandDecode();?>
        <script type="text/x-magento-init">
        {
                "#product_addtocart_form": {
                    "MageArray_Customprice/js/customprice": {
                        "optionConfig": <?= /* @escapeNotVerified */ $data?>,
                        "controlContainer": ".field",
                        "priceHolderSelector": "[data-role=priceBox]"
                    }
                }
            }
        </script>
    <?php endif;?>
<?php endif;?>
<script type="text/javascript">
    var itemQty = '<?= $block->getItemQty() ?>';
    var productConfigureMode = '<?= $block->getConfigureMode(); ?>';
</script>