<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2018 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php
/**
 * @see \Blackbird\ContentManager\Block\View
 */
?>
<?php
/*
 * 
 * 
 * AVAILABLE METHODS
 * 
 * Get all raw values as an array
 * $content->getData();
 * 
 * Get a specific value by his field identifier
 * $content->getData('field_identifier');
 * $content->getFieldIdentifier();
 * $content->getAttributeText('field_identifier');
 * 
 * Get content type model
 * $content->getContentType();
 * 
 * Get image URL for an image field type.
 * $content->getImage($attributeName, $width, $height, $keepRatio, $cropped = false);
 * 
 * Get file absolute URL, for a file field typ
 * $content->getFile($field_identifier);
 * 
 * Get content url
 * $content->getLinkUrl();
 * 
 * Render a field in HTML
 * $content->render($element, $params);
 * 
 * See the complete documentation and more examples at:
 * http://www.advancedcontentmanager.com/documentation/
 * 
 */
?>

<?php
    // Object manager and collection
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
    $_contentCollection = $_objectManager->create('Blackbird\ContentManager\Model\ResourceModel\Content\CollectionFactory'); 

    // Helpers
    $_coreHelper = $this->helper('\Magezon\Core\Helper\Data');
    $_builderHelper = $this->helper('\Magezon\Builder\Helper\Data');

    // ACM data
    /** @var \Blackbird\ContentManager\Model\Content $content */
    $_item = $block->getContent();
    /** @var \Blackbird\ContentManager\Model\ContentType $contentType */
    $_contentType = $_item->getContentType();

    // Content-type data
    $_identifier = $_contentType != null ? $_contentType->getData('identifier') : "";
    $_prefix = $_identifier . "_";

    // Common Content (Prefixed with the content-type slug, i.e - "job_subtitle")
    // Excluding "title", which is always there
    $title = $_item->getData("title");

    $read_time = $_item->getData("blog_read_time");
    $blog_author = $_item->getData("blog_blog_author");
    $blog_entry_date = $_item->getData("blog_entry_date");
    $blog_banner_image = $_item->getData("blog_banner_image");

    $subtitle = $_item->getData($_prefix . "subtitle");
    $content = $_coreHelper->filter($_item->getData($_prefix . 'content')); // Use the Magezon helper because PageBuilder will be applied to rich-text editor field types
    $subcontent = $_coreHelper->filter($_item->getData($_prefix . 'subcontent')); // Use the Magezon helper because PageBuilder will be applied to rich-text editor field types

    // Image data
    $image = !empty($_item->getData($_prefix . 'image')) ? $_item->getImage($_prefix . "image", $width = null, $height = null, $keepAspectRatio = false, $cropped = false) : null;
    $image_src = !empty($image) ? $image : "";

    $preview_image = !empty($_item->getData($_prefix . 'preview_image')) ? $_item->getImage($_prefix . "preview_image", $width = null, $height = null, $keepAspectRatio = false, $cropped = false) : null;
    $preview_image_src = !empty($preview_image) ? $preview_image : "";
    ?>

    <div class="media-text-block content-block container-height-large horizontal-start" style="margin-top:0;">
        <div class="container">
            <div class="row is-flex">
                <div class="col-md-6 image-container second">
                    <div class="image" style="background-image:url('/assets/img/jamie.png')">
                    </div>
                </div>
                <div class="col-md-6 content-container first ">
                    <div class="content">
                        <h6>Discover</h6>
                        <h3><?php echo $title; ?></h3>

                          <?php

                                $authorattributes = array(
                                    'entity_id',
                                    'title',
                                    'blog_author_image'
                                );

                                $authors = $_contentCollection
                                ->create()
                                ->addContentTypeFilter('blog_author')
                                ->addAttributeToFilter('entity_id', array('in' => array((int)$blog_author)))
                                ->addAttributeToFilter('status', 1)
                                ->addAttributeToSelect($authorattributes);

                                foreach ($authors as $author) { 

                                    $image = $author->getImage("blog_author_image");

                                    ?>

                        <div class="author">
                            <div class="author-image">
                                <img style="border-radius:50%;" src="<?php echo $image; ?>" alt="">
                            </div>
                            <div class="author-details" style="padding-left:15px;">
                              
                                
                                <p><?php echo $author->getTitle(); ?></p>

                        
                                <p><?php echo $blog_entry_date; ?> - <?php echo $read_time; ?></p>
                            </div>
                        </div>

                            <?php }?>
                        <ul class="social-media no-bullet">
                            <li><a href=""><i class="fa fa-instagram"></i></a></li>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href=""><i class="fa fa-pinterest"></i></a></li>
                            <li><a href=""><i class="fa fa-youtube"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="article-content-block">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="user-content">
                        <?php echo $content; ?>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="article-sidebar">
                        <div class="article-banner">
                            <img src="/assets/img/essentials.png" alt="">
                        </div>
                        <ul class="social-media no-bullet">
                            <li><a href=""><i class="fa fa-instagram"></i></a></li>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href=""><i class="fa fa-pinterest"></i></a></li>
                            <li><a href=""><i class="fa fa-youtube"></i></a></li>
                        </ul>
                        <div class="newsletter-signup-sidebar">
                            <form action="">
                                <fieldset>
                                    <h3>Sign Up</h3>
                                    <div class="input-button">
                                        <input placeholder="jane.smith@yahoo.com" type="text"><button><i class="fa fa-chevron-right"></i></button>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>