<?php
// Simple block used to show the unit price when a product is viewed in the trade site.
// Treats the default store as the source of the unit price

// Get the currently viewed product
$_consumerStoreId = 1;
$_product = $block->getProduct();
$_storeManager = $block->getStoreManager();
$_customerSession = $block->getCustomerSession();
$_finalPrice = $block->getFinalPriceForStore($_product->getId(), $_consumerStoreId);
$_rrpPrice = $block->getRRPForStore($_product->getId(), $_consumerStoreId);
$_unitPrice = $block->getUnitPriceForStore($_product->getId(), $_consumerStoreId);
?>

<?php if($_storeManager->getWebsite()->getCode() == 'trade' && $_unitPrice > 0): ?>
    <div class="unit-price-container">
        <span class="label"><?php echo __('Unit'); ?></span>
        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_unitPrice, true, true); ?>
    </div>
<?php endif; ?>