<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
    <div class="category-description">
    	<h2><?php echo $block->getCurrentCategory()->getName() ;?>.</h2>
    	<?php if ($_description = $block->getCurrentCategory()->getDescription()) :?>

        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $_description,
            'description'
        ) ?>
        <?php endif; ?>
    </div>

