<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">

    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-target="dropdown">

            <li>
                                <img src="/assets/img/flag-<?= strtolower($block->escapeHtml($block->getCurrentStoreCode())) ?>.png">
<ul>
            
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                        <a href="javascript:void(0)" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'>
                            <img src="/assets/img/flag-<?= strtolower($block->escapeHtml($_lang->getCode())) ?>.png">
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </li>
        </ul>
    </div>
</div>