    <div class="contact-block" style="margin:0;">
        <div class="media-text-block content-block horizontal-start" style="margin-bottom:0;margin-top:0;">
            <div class="container">
                <div class="row is-flex">
                    <div class="col-md-6 image-container second height-large">
                        <div class="image" style="background-image:url('/pub/media/Ilana.jpg')">
                        </div>
                    </div>
                    <div class="col-md-6 content-container first">
                        <div class="content">
                           <h3 style="text-transform:uppercase;"><i>Get In Touch</i></h3>
                           <p><strong>Email: <a style="color:#333;" href="mailto:support@vieve.co.uk">support@vieve.co.uk</a></p>
		           <p><strong>Call Us: </strong><a style="color:#333;" href="tel:020 3011 0960">020 3011 0960</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 
        <div id="trust-bar" style="display:none">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="trust-mark">
                            <div class="center">
                                <div>
                                    <div class="image">                 
                                        <img src="/assets/img/delivery.png" alt="">
                                    </div>
                                    <div class="content">
                                        <h6>Email Us</h6>
                                        <p><a href="mailto:support@vieve.co.uk">support@vieve.co.uk</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="trust-mark">
                            <div class="center">
                                <div>
                                    <div class="image">                 
                                        <img src="/assets/img/return-policy.png" alt="">
                                    </div>
                                    <div class="content">
                                        <h6>Call Us</h6>
                                        <p><a href="tel:020 3011 0960">020 3011 0960</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="trust-mark">
                            <div class="center">
                                <div>
                                    <div class="image">                 
                                        <img src="/assets/img/need-help.png" alt="">
                                    </div>
                                    <div class="content">
                                        <h6>Follow Us</h6>
                                        <p><a href="https://www.twitter.com/vievemuse">@VIEVEmuse</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>                              
                    </div>
                </div>
            </div>
        </div>
    </div>