<?php
    // Class ref: \Parachute\PageBuilderExtension\Data\Element\ContentListings

    // Helpers
    $_coreHelper = $this->helper('\Magezon\Core\Helper\Data');
    $_builderHelper = $this->helper('\Magezon\Builder\Helper\Data');

    // Element data
    $_element = $this->getElement();
    $_id = time() . uniqid();

    // foreach($_element->getData() as $key=>$value):
    //     echo '<pre>' . $key . '</pre>';
    //     print_r($value);
    // endforeach;

    // Layout
    // Block classes
    $block_class_str = "";
    $block_class_arr = [];

    // Block container classes
    $block_container_class_str = "";
    $block_container_class_arr = [];

    // Block inner classes
    $block_inner_class_str = "";
    $block_inner_class_arr = [];

    // Block inner container classes
    $block_inner_container_class_str = "";
    $block_inner_container_class_arr = [];

    // Listings classes
    $listings_class_str = "";
    $listings_class_arr = [];

    // Block
    $block_active = $_element->getData('block_active');
    $block_title = $_element->getData('block_title');
    $block_subtitle = $_element->getData('block_subtitle');
    $block_content = $_element->getData('block_content');
    $block_subcontent = $_element->getData('block_subcontent');

    // Block CTA
    $block_cta_type = $_element->getData('block_cta_type');
    $block_cta_target = $_element->getData('block_cta_target');
    $block_cta_link = $_element->getData('block_cta_link');
    $block_cta_link_text = !empty($_element->getData('block_cta_link_text')) ? $_element->getData('block_cta_link_text') : "Read more";

    // Block sub-content CTA
    $block_subcontent_cta_type = $_element->getData('block_subcontent_cta_type');
    $block_subcontent_cta_target = $_element->getData('block_subcontent_cta_target');
    $block_subcontent_cta_link = $_element->getData('block_cta_subcontent_link');
    $block_subcontent_cta_link_text = !empty($_element->getData('block_subcontent_cta_link_text')) ? $_element->getData('block_subcontent_cta_link_text') : "Read more";

    $block_header_show = boolval($_element->getData('block_header_show')) ? $_element->getData('block_header_show') : false;
    $block_footer_show = boolval($_element->getData('block_footer_show')) ? $_element->getData('block_footer_show') : false;
    $block_layout = !empty($_element->getData("layout_type")) ? $_element->getData("layout_type") : "content";
    $block_header_has_data = false;
    $block_footer_has_data = false;

    // Does our header have any content?
    if(
        !empty($block_title) || 
        !empty($block_subtitle) || 
        !empty($block_content) || 
        !empty($block_subcontent) || 
        !empty($block_cta_link)) 
    {
        $block_header_has_data = true;
        $block_footer_has_data = true;
    }

    // Layout type classes
    if(!empty($block_layout))
    {
        $block_class_arr[] = $block_layout;
        $block_class_arr[] = $block_layout . "-listings-block";
        $listings_class_arr[] = $block_layout;
    }

    // Block images
    // Primary image
    $block_image = $_element->getData('block_image');
    $block_image_src = !empty($_builderHelper->getImageUrl($block_image)) ? $_builderHelper->getImageUrl($block_image) : "";
    $block_image_background_type = $_element->getData('block_image_background_type');
    $block_image_video_url = $_element->getData('block_image_video_url');
    $block_image_youtube_id = $_element->getData('block_image_youtube_id');
    $block_image_vimeo_id = $_element->getData('block_image_vimeo_id');

    // Secondary image
    $block_secondary_image = $_element->getData('block_secondary_image');
    $block_secondary_image_src = !empty($_builderHelper->getImageUrl($block_secondary_image)) ? $_builderHelper->getImageUrl($block_secondary_image) : "";
    $block_secondary_image_background_type = $_element->getData('block_secondary_image_background_type');
    $block_secondary_image_video_url = $_element->getData('block_secondary_image_video_url');
    $block_secondary_image_youtube_id = $_element->getData('block_secondary_image_youtube_id');
    $block_secondary_image_vimeo_id = $_element->getData('block_secondary_image_vimeo_id');

    // Block mage list
    $block_image_list = $this->toObjectArray($_element->getData('block_image_list'));

    // Items
    $_items = $this->toObjectArray($_element->getItems());
    $_row_limit = $_element->getData("row_limit") != null && is_numeric($_element->getData("row_limit")) && $_element->getData("row_limit") > 0 ? 
        $_element->getData('row_limit') : 3;

    // Row item limit & item layout classes
    $_item_layout_class = "";

    switch($_row_limit)
    {
        case 1:
            $_item_layout_class = "col-xs-12 col-sm-12 col-md-12";
        break;

        case 2:
            $_item_layout_class = "col-xs-12 col-sm-6 col-md-6";
        break;

        case 3:
            $_item_layout_class = "col-xs-12 col-sm-4 col-md-4";
        break;

        case 4:
            $_item_layout_class = "col-xs-12 col-sm-3 col-md-3";
        break;

        case 6:
            $_item_layout_class = "col-xs-12 col-sm-2 col-md-2";
        break;

        case 12:
            $_item_layout_class = "col-xs-12 col-sm-1 col-md-1";
        break;

        default:
            $_item_layout_class = "col-xs-12 col-sm-4 col-md-4";
        break;
    }

    $_item_layout_class_str = $_item_layout_class != "" ? $_item_layout_class : "col-xs-12 col-sm-4 col-md-4";
    if($_item_layout_class == "") { $_row_limit = 3; }

    $block_class_arr[] = "row-item-item-limit-" . $_row_limit;
    $listings_class_arr[] = "row-item-limit-" . $_row_limit;

    // Layout
    $layout_type = !empty($_element->getData('layout_type')) ? $_element->getData('layout_type') : "";
    $text_align = !empty($_element->getData('text_align')) ? $_element->getData('text_align') : "centre";
    $content_align = !empty($_element->getData('content_align')) ? $_element->getData('content_align') : "centre";
    $content_justify = !empty($_element->getData('content_justify')) ? $_element->getData('content_justify') : "centre";
    $alignment = !empty($_element->getData('alignment')) ? $_element->getData('alignment') : "left";
    $content_size = !empty($_element->getData('content_size')) ? $_element->getData('content_size') : "medium";

    $block_class_arr[] = $layout_type;
    $block_class_arr[] = "text-align-" . $text_align;
    $block_class_arr[] = "align-content-" . $content_align;
    $block_class_arr[] = "justify-content-" . $content_justify;
    $block_class_arr[] = "align-" . $alignment;
    $block_class_arr[] = $content_size;
    
    $container_outer_type = !empty($_element->getData('container_type')) ? $_element->getData('container_type') : "container-fluid";
    $container_outer_type_str = $container_outer_type == "fixed" ? "container" : "container-fluid";

    $container_inner_type = !empty($_element->getData('container_type_inner')) ? $_element->getData('container_type_inner') : "container";
    $container_inner_type_str = $container_inner_type == "fixed" ? "container" : "container-fluid";

    $no_gutter = $_element->getData('no_gutter');
    $no_gutter_inner = $_element->getData('no_gutter_inner');

    $block_container_class_arr[] = $container_outer_type_str;
    $block_inner_container_class_arr[] = $container_inner_type_str;

    if(!empty($no_gutter)) { $block_class_arr[] = "no-gutter"; }
    if(!empty($no_gutter_inner)) { $block_inner_container_class_arr[] = "no-gutter"; }

    // Carousel Options

    // General

    // Design Options

    // Generate class string
    // For the block
    if(!empty($block_class_arr))
        $block_class_str = join(" ", $block_class_arr);

    // Block container
    if(!empty($block_container_class_arr))
        $block_container_class_str = join(" ", $block_container_class_arr);

    // Inner block
    if(!empty($block_inner_class_arr))
        $block_inner_class_str = join(" ", $block_inner_class_arr);

    // Inner block container
    if(!empty($block_inner_container_class_arr))
        $block_inner_container_class_str = join(" ", $block_inner_container_class_arr);

    // Listings
    if(!empty($listings_class_arr))
        $listings_class_str = join(" ", $listings_class_arr);

    // Loop vars
    $item_count = count($_items);
    $counter = 0;
    $loop = 1;
?>

<?php if(!empty($block_active)): ?>
    <div id="block-<?php echo $_id; ?>" class="content-listings-block content-block<?php echo !empty($block_class_str) ? " " . $block_class_str : ""; ?>">
        <div class="content-listings-block-inner content-block-inner">
            <div class="content-listings-block-inner-container content-block-inner-container<?php echo !empty($block_container_class_str) ? " " . $block_container_class_str : " container"; ?>">
                <div class="content-listings-block-inner-row content-block-inner-row row">
                    <div class="content-listings-block-inner-content content-block-inner-content col-xs-12 col-sm-12 col-md-12">
                        <div class="content-block-content-container<?php echo !empty($block_inner_container_class_str) ? " " . $block_inner_container_class_str : " container-fluid no-gutter"; ?>">
                            <div class="content-block-content-container-row row">
                                <!-- Content Header -->
                                <?php if($block_header_has_data == true && $block_header_show == true): ?>
                                    <div class="content-listings-header content-block-header">
                                        <div class="content-listings-header-inner content-block-header-inner">
                                            <div class="content-listings-header-titles content-block-header-titles">
                                                <?php if(!empty($block_title)): ?>
                                                    <h3 class="content-listings-header-title content-block-header-title">
                                                        <?php echo $block_title; ?>
                                                    </h3>
                                                <?php endif; ?>

                                                <?php if(!empty($block_subtitle)): ?>
                                                    <h4 class="content-listings-header-subtitle content-block-header-subtitle">
                                                        <?php echo $block_subtitle; ?>
                                                    </h4>
                                                <?php endif; ?>
                                            </div>

                                            <?php if(!empty($block_content)): ?>
                                                <div class="content-listings-description content-block-description">
                                                    <?php echo $block_content; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if(!empty($block_cta_link)): ?>
                                                <div class="content-listings-header-links content-block-links">
                                                    <div class="content-listings-header-links-inner content-block-links-inner">
                                                        <ul class="content-listings-header-links-list content-block-links-list">
                                                            <li class="content-listings-header-link-item content-block-links-list-item link-item item">
                                                                <a href="<?php echo $block_cta_link; ?>" class="button" title="<?php echo $block_cta_link_text; ?>">
                                                                    <?php echo $block_cta_link_text; ?>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <!-- End Content Header -->

                                <!-- Content -->
                                <div class="content-block-content">
                                    <?php if(!empty($_items)): ?>
                                        <?php foreach($_items as $_item): ?>
                                            <?php 
                                                // Active
                                                $active = $_item->getData('active');

                                                // Skip if it isn't active!
                                                if($active != "1")
                                                {
                                                    $loop++; 
                                                    continue;
                                                }

                                                // Content
                                                $title = $_item->getData('title');
                                                $subtitle = $_item->getData('subtitle');
                                                $subcontent = $_item->getData('subcontent');
                                                $content = $_item->getData('content');
                                                $footer_title = $_item->getData('footer_title');
                                                $image = $_item->getData('image');
                                                $image_src = !empty($_builderHelper->getImageUrl($image)) ? $_builderHelper->getImageUrl($image) : "";
                                                $secondary_image = $_item->getData('secondary_image');
                                                $secondary_image_src = !empty($_builderHelper->getImageUrl($secondary_image)) ? $_builderHelper->getImageUrl($secondary_image) : "";

                                                // Image list
                                                $image_list = $this->toObjectArray($_item->getData('image_list'));

                                                // CTA
                                                $cta_link = $_item->getData('cta_link');
                                                $cta_link_text = !empty($_item->getData('cta_link_text')) ? $_item->getData('cta_link_text') : "Learn more";
                                                $secondary_cta_link = $_item->getData('secondary_cta_link');
                                                $secondary_cta_link_text = !empty($_item->getData('secondary_cta_link_text')) ? $_item->getData('secondary_cta_link_text') : "Learn more";

                                                // Layout
                                                $class_str = "";
                                                $class_arr = [];
                                                
                                                $banner_type = !empty($_item->getData('layout_type')) ? $_item->getData('layout_type') : "content";
                                                $text_align = !empty($_item->getData('text_align')) ? $_item->getData('text_align') : "left";
                                                $content_align = !empty($_item->getData('content_align')) ? $_item->getData('content_align') : "start";
                                                $content_justify = !empty($_item->getData('content_justify')) ? $_item->getData('content_justify') : "start";
                                                $alignment = !empty($_item->getData('alignment')) ? $_item->getData('alignment') : "left";
                                                $content_size = !empty($_item->getData('content_size')) ? $_item->getData('content_size') : "medium";

                                                $class_arr[] = $banner_type;
                                                $class_arr[] = "text-align-" . $text_align;
                                                $class_arr[] = "align-content-" . $content_align;
                                                $class_arr[] = "justify-content-" . $content_justify;
                                                $class_arr[] = "align-" . $alignment;
                                                $class_arr[] = $content_size;

                                                // Generate class string
                                                if(!empty($class_arr))
                                                {
                                                    $class_str = join(" ", $class_arr);
                                                }

                                                // foreach($_item->getData() as $key=>$value):
                                                //     echo '<pre>' . $key . '</pre>';
                                                //     print_r($value);
                                                // endforeach;
                                            ?>

                                            <?php if($counter == 0): ?>
                                                <ul class="content-listings content-listings-row<?php echo !empty($listings_class_str) ? " " . $listings_class_str : ""; ?> row">
                                            <?php endif; ?>

                                            <li class="content-listing content-listing-item content-item item<?php echo !empty($class_str) ? " " . $class_str : ""; ?> <?php echo $_item_layout_class_str; ?>">
                                                <div class="content-item-inner">
                                                    <?php if(!empty($image_src)): ?>
                                                        <div class="content-item-image">
                                                            <div class="content-item-image-inner" style="background-image:url(<?php echo $image_src; ?>)">
                                                                <?php if(!empty($cta_link)): ?>
                                                                    <a href="<?php echo $cta_link; ?>" title="<?php echo $cta_link_text; ?>">
                                                                <?php endif; ?>
                                                                
                                                                <img src="<?php echo $image_src; ?>" alt="<?php echo $title; ?> Image" title="<?php echo $title; ?>">

                                                                <?php if(!empty($cta_link)): ?>
                                                                    </a>
                                                                <?php endif; ?>
                                                            </div>
                                                        </div>
                                                    <?php endif; ?>

                                                    <div class="content-item-content">
                                                        <div class="content-item-content-inner">
                                                            <div class="content-item-header">
                                                                <div class="content-item-header-inner">
                                                                    <h3 class="content-item-title">
                                                                        <?php echo $title; ?>
                                                                    </h3>

                                                                    <?php if(!empty($subtitle)): ?>
                                                                        <h4 class="content-item-subtitle">
                                                                            <?php echo $subtitle; ?>
                                                                        </h4>
                                                                    <?php endif; ?>
                                                                </div>
                                                            </div>

                                                            <div class="content">
                                                                <div class="content-inner">
                                                                    <?php echo $content; ?>
                                                                </div>
                                                            </div>

                                                            <?php if(!empty($footer_title)): ?>
                                                                <div class="content-item-footer">
                                                                    <div class="content-item-footer-inner">
                                                                        <h5 class="footer-title">
                                                                            <?php echo $footer_title; ?>
                                                                        </h5>
                                                                    </div>
                                                                </div>
                                                            <?php endif; ?>

                                                            <?php if(!empty($cta_link)): ?>
                                                                <div class="content-item-links">
                                                                    <div class="content-item-links-inner">
                                                                        <ul class="content-item-links-list">
                                                                            <li class="content-item-link">
                                                                                <a href="<?php echo $cta_link; ?>" title="<?php echo $cta_link_text; ?>" class="button">
                                                                                    <span class="text"><?php echo $cta_link_text; ?></span>

                                                                                    <span class="icon-container">

                                                                                    </span>
                                                                                </a>
                                                                            </li>
                                                                        </ul>
                                                                    </div>
                                                                </div>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>

                                            <?php if($counter == $_row_limit - 1 || $loop == $item_count): ?>
                                                </ul> <!-- .content-listings -->
                                                <?php $counter = 0; ?>
                                            <?php else: ?>
                                                <?php $counter++; $loop++; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </div>
                                <!-- End Content -->

                                <!-- Content Footer -->
                                <?php if($block_footer_has_data == true && $block_footer_show == true && !empty($block_cta_link)): ?>
                                    <div class="content-block-footer content-listings-footer">
                                        <div class="content-block-footer-inner content-listings-footer-inner">
                                            <?php if(!empty($block_cta_link)): ?>
                                                <ul class="content-block-footer-links-list content-listings-footer-links-list">
                                                    <li class="content-block-footer-link content-listings-footer-link footer-link">
                                                        <a href="<?php echo $block_cta_link; ?>" title="<?php echo $block_cta_link_text; ?>" class="button">
                                                            <span class="text"><?php echo $block_cta_link_text; ?></span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <!-- End Content Footer -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>