
<div class="newsletter-block content-block">
	<div class="container">
		<div class="row is-flex">
			<div class="col-md-4">
				<h2>Become A Muse</h2>
			</div>
			<div class="col-md-8">
				<form action="">

					<input placeholder="Your Name" type="name">
					<input type="email" placeholder="Email Address">
					<button class="button button-black">Join Vieve</button>
				</form>

			</div>
		</div>
	</div>
</div>