<?php
    // Class ref: \Parachute\PageBuilderExtension\Data\Element\Banner

    // Helpers
$_coreHelper = $this->helper('\Magezon\Core\Helper\Data');
$_builderHelper = $this->helper('\Magezon\Builder\Helper\Data');

    // Element data
$_element = $this->getElement();
$_id = time() . uniqid();

    // foreach($_element->getData() as $key=>$value):
    //     echo '<pre>' . $key . '</pre>';
    //     print_r($value);
    // endforeach;

    // Layout
    // Block classes
$block_class_str = "";
$block_class_arr = [];

    // Block container classes
$block_container_class_str = "";
$block_container_class_arr = [];

    // Block inner classes
$block_inner_class_str = "";
$block_inner_class_arr = [];

    // Block inner container classes
$block_inner_container_class_str = "";
$block_inner_container_class_arr = [];

    // Listings classes
$listings_class_str = "";
$listings_class_arr = [];

    // Block
$block_active = $_element->getData('block_active');
$block_title = $_element->getData('block_title');
$block_subtitle = $_element->getData('block_subtitle');
$block_content = $_element->getData('block_content');
$block_subcontent = $_element->getData('block_subcontent');
$block_cta_type = $_element->getData('block_cta_type');
$block_cta_target = $_element->getData('block_cta_target');
$block_cta_link = $_element->getData('block_cta_link');
$block_cta_link_text = $_element->getData('block_cta_link_text');
$block_image = $_element->getData('block_image');
$block_header_show = boolval($_element->getData('block_header_show')) ? $_element->getData('block_header_show') : false;
$block_footer_show = boolval($_element->getData('block_footer_show')) ? $_element->getData('block_footer_show') : false;
$block_layout = !empty($_element->getData("layout_type")) ? $_element->getData("layout_type") : "content";
$block_header_has_data = false;
$block_footer_has_data = false;

    // Does our header have any content?
if(
    !empty($block_title) || 
    !empty($block_subtitle) || 
    !empty($block_content) || 
    !empty($block_subcontent) || 
    !empty($block_cta_link)) 
{
    $block_header_has_data = true;
    $block_footer_has_data = true;
}

    // Layout type classes
if(!empty($block_layout))
{
    $block_class_arr[] = $block_layout;
    $listings_class_arr[] = $block_layout;
}

    // Image list
$block_image_list = $this->toObjectArray($_element->getData('block_image_list'));

    // Items
$_items = $this->toObjectArray($_element->getItems());

    // Carousel
$isCarouselActive = boolval($_element->getData('is_carousel_active')) ? $_element->getData('is_carousel_active') : false;
if($isCarouselActive) { $block_class_arr[] = "is-carousel"; }
if($isCarouselActive) { $listings_class_arr[] = "is-carousel"; }

    // Layout
$layout_type = !empty($_element->getData('layout_type')) ? $_element->getData('layout_type') : "";
$text_align = !empty($_element->getData('text_align')) ? $_element->getData('text_align') : "left";
$content_align = !empty($_element->getData('content_align')) ? $_element->getData('content_align') : "start";
$content_justify = !empty($_element->getData('content_justify')) ? $_element->getData('content_justify') : "start";
$alignment = !empty($_element->getData('alignment')) ? $_element->getData('alignment') : "left";
$content_size = !empty($_element->getData('content_size')) ? $_element->getData('content_size') : "medium";

$block_class_arr[] = $layout_type;
$block_class_arr[] = "text-align-" . $text_align;
$block_class_arr[] = "align-content-" . $content_align;
$block_class_arr[] = "justify-content-" . $content_justify;
$block_class_arr[] = "align-" . $alignment;
$block_class_arr[] = $content_size;

$container_outer_type = !empty($_element->getData('container_type')) ? $_element->getData('container_type') : "container-fluid";
$container_outer_type_str = $container_outer_type == "fixed" ? "container" : "container-fluid";

$container_inner_type = !empty($_element->getData('container_type_inner')) ? $_element->getData('container_type_inner') : "container";
$container_inner_type_str = $container_inner_type == "fixed" ? "container" : "container-fluid";

$no_gutter = $_element->getData('no_gutter');
$no_gutter_inner = $_element->getData('no_gutter_inner');

$block_container_class_arr[] = $container_outer_type_str;
$block_inner_container_class_arr[] = $container_inner_type_str;

if(!empty($no_gutter)) { $block_class_arr[] = "no-gutter"; }
if(!empty($no_gutter_inner)) { $block_inner_container_class_arr[] = "no-gutter"; }


if(!empty($block_class_arr))
    $block_class_str = join(" ", $block_class_arr);

    // Block container
if(!empty($block_container_class_arr))
    $block_container_class_str = join(" ", $block_container_class_arr);

    // Inner block
if(!empty($block_inner_class_arr))
    $block_inner_class_str = join(" ", $block_inner_class_arr);

    // Inner block container
if(!empty($block_inner_container_class_arr))
    $block_inner_container_class_str = join(" ", $block_inner_container_class_arr);

    // Listings
if(!empty($listings_class_arr))
    $listings_class_str = join(" ", $listings_class_arr);

    // Loop vars
$item_count = count($_items);
$counter = 0;
$loop = 1;
?>

<div class="quote-container content-block">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <blockquote>
                <h2 id="typedtext"><?php echo $block_title; ?></h2>
                </blockquote>
            </div>
        </div>
    </div>
</div>

<!-- <script>
    



// set up text to print, each item in array is new line
var aText = new Array(
"When you become your own Muse you inspire yourself and, in turn, can inspire others.", 

);
var iSpeed = 100; // time delay of print out
var iIndex = 0; // start printing array at this posision
var iArrLength = aText[0].length; // the length of the text array
var iScrollAt = 20; // start scrolling up at this many lines
 
var iTextPos = 0; // initialise text position
var sContents = ''; // initialise contents variable
var iRow; // initialise current row
 
function typewriter()
{
 sContents =  ' ';
 iRow = Math.max(0, iIndex-iScrollAt);
 var destination = document.getElementById("typedtext");
 
 while ( iRow < iIndex ) {
  sContents += aText[iRow++] + '<br />';
 }
      destination.innerHTML = sContents + aText[iIndex].substring(0, iTextPos) + "<span>_</span>";



 if ( iTextPos++ == iArrLength ) {

  iTextPos = 0;
  iIndex++;
  if ( iIndex != aText.length ) {
   iArrLength = aText[iIndex].length;
   setTimeout("typewriter()", 300);
  }
 } else {
  setTimeout("typewriter()", iSpeed);
 }
}


typewriter();


</script> -->