<?php

?>



<div class="start-earning-points">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <header class="content-header content-header-line">
                    <h2>Start Earning Points</h2>
                </header>

            </div>
        </div>

        <div class="row">
          <div class="col-md-4 earning-item">
              <h5>Step 1</h5>
              <img src="/assets/img/envelope.png" alt="">
              <h3>Sign Up</h3>
              <p>Create an account with your name and email</p>
          </div>
          <div class="col-md-4 earning-item">
           <h5>Step 2</h5>
           <img src="/assets/img/lipstick-reward.png" alt="">
           <h3>Collect Points</h3>
           <p>Easily collect points to enjoy exclusive rewards</p> 
       </div>

       <div class="col-md-4 earning-item">
           <h5>Step 3</h5>
           <img src="/assets/img/gift.png" alt="">
           <h3>Enjoy Rewards</h3>
           <p>Redeem your points against your next purchase</p> 
       </div>
   </div> 
   <div class="row">
      <div class="col-md-12">
          <a href="#" class="button">Sign up or login here</a>
      </div>
  </div>
</div>
</div>


<div class="how-to-earn-points">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <header class="content-header content-header-line">
                    <h2>How to earn VIEVE points</h2>
                </header>

            </div>
        </div>

<div data-lion-rules-list=""></div>

</div>

</div>


<div class="how-to-spend-pints">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <header class="content-header content-header-line">
                    <h2>How to spend VIEVE points</h2>
                </header>
            </div>
        </div>
        <div data-lion-rewards-list></div>
    </div>
</div>