<?php
    // Class ref: \Parachute\PageBuilderExtension\Data\Element\TextPanel

    // Helpers
    $_coreHelper = $this->helper('\Magezon\Core\Helper\Data');
    $_builderHelper = $this->helper('\Magezon\Builder\Helper\Data');

    // Element data
    $_element = $this->getElement();
    $_id = time() . uniqid();

    // foreach($_element->getData() as $key=>$value):
    //     echo '<pre>' . $key . '</pre>';
    //     print_r($value);
    // endforeach;

    // Layout
    // Block classes
    $block_class_str = "";
    $block_class_arr = [];

    // Block container classes
    $block_container_class_str = "";
    $block_container_class_arr = [];

    // Block inner classes
    $block_inner_class_str = "";
    $block_inner_class_arr = [];

    // Block inner container classes
    $block_inner_container_class_str = "";
    $block_inner_container_class_arr = [];

    // Listings classes
    $listings_class_str = "";
    $listings_class_arr = [];

    // Block
    $block_active = $_element->getData('block_active');
    $block_title = $_element->getData('block_title');
    $block_subtitle = $_element->getData('block_subtitle');
    $block_content = $_element->getData('block_content');
    $block_subcontent = $_element->getData('block_subcontent');
    $block_background = $_element->getData('block_background');

    // Block CTA
    $block_cta_type = $_element->getData('block_cta_type');
    $block_cta_target = $_element->getData('block_cta_target');
    $block_cta_link = $_element->getData('block_cta_link');
    $block_cta_link_text = !empty($_element->getData('block_cta_link_text')) ? $_element->getData('block_cta_link_text') : "Read more";

    // Block sub-content CTA
    $block_subcontent_cta_type = $_element->getData('block_subcontent_cta_type');
    $block_subcontent_cta_target = $_element->getData('block_subcontent_cta_target');
    $block_subcontent_cta_link = $_element->getData('block_cta_subcontent_link');
    $block_subcontent_cta_link_text = !empty($_element->getData('block_subcontent_cta_link_text')) ? $_element->getData('block_subcontent_cta_link_text') : "Read more";

    $block_header_show = boolval($_element->getData('block_header_show')) ? $_element->getData('block_header_show') : false;
    $block_footer_show = boolval($_element->getData('block_footer_show')) ? $_element->getData('block_footer_show') : false;
    $block_layout = !empty($_element->getData("layout_type")) ? $_element->getData("layout_type") : "content";
    $block_layout = "text-panel"; // Hardcoded
    $block_header_has_data = false;
    $block_footer_has_data = false;

    // Does our header have any content?
    if(
        !empty($block_title) || 
        !empty($block_subtitle) || 
        !empty($block_content) || 
        !empty($block_subcontent) || 
        !empty($block_cta_link)) 
    {
        $block_header_has_data = true;
        $block_footer_has_data = true;
    }

    // Layout type classes
    if(!empty($block_layout))
    {
        $block_class_arr[] = $block_layout;
        $listings_class_arr[] = $block_layout;
    }

    // Block images
    // Primary image
    $block_image = $_element->getData('block_image');
    $block_image_src = !empty($_builderHelper->getImageUrl($block_image)) ? $_builderHelper->getImageUrl($block_image) : "";
    $block_image_background_type = $_element->getData('block_image_background_type');
    $block_image_video_url = $_element->getData('block_image_video_url');
    $block_image_youtube_id = $_element->getData('block_image_youtube_id');
    $block_image_vimeo_id = $_element->getData('block_image_vimeo_id');

    // Secondary image
    $block_secondary_image = $_element->getData('block_secondary_image');
    $block_secondary_image_src = !empty($_builderHelper->getImageUrl($block_secondary_image)) ? $_builderHelper->getImageUrl($block_secondary_image) : "";
    $block_secondary_image_background_type = $_element->getData('block_secondary_image_background_type');
    $block_secondary_image_video_url = $_element->getData('block_secondary_image_video_url');
    $block_secondary_image_youtube_id = $_element->getData('block_secondary_image_youtube_id');
    $block_secondary_image_vimeo_id = $_element->getData('block_secondary_image_vimeo_id');

    // Block image list
    $block_image_list = $this->toObjectArray($_element->getData('block_image_list'));

    // Layout
    $layout_type = !empty($_element->getData('layout_type')) ? $_element->getData('layout_type') : "text-panel";
    $text_align = !empty($_element->getData('text_align')) ? $_element->getData('text_align') : "centre";
    $content_align = !empty($_element->getData('content_align')) ? $_element->getData('content_align') : "centre";
    $content_justify = !empty($_element->getData('content_justify')) ? $_element->getData('content_justify') : "centre";
    $alignment = !empty($_element->getData('alignment')) ? $_element->getData('alignment') : "left";
    $content_size = !empty($_element->getData('content_size')) ? $_element->getData('content_size') : "medium";

    $block_class_arr[] = $layout_type;
    $block_class_arr[] = "text-align-" . $text_align;
    $block_class_arr[] = "align-content-" . $content_align;
    $block_class_arr[] = "justify-content-" . $content_justify;
    $block_class_arr[] = "align-" . $alignment;
    $block_class_arr[] = $content_size;
    
    $container_outer_type = !empty($_element->getData('container_type')) ? $_element->getData('container_type') : "container-fluid";
    $container_outer_type_str = $container_outer_type == "fixed" ? "container" : "container-fluid";

    $container_inner_type = !empty($_element->getData('container_type_inner')) ? $_element->getData('container_type_inner') : "container";
    $container_inner_type_str = $container_inner_type == "fixed" ? "container" : "container-fluid";

    $no_gutter = $_element->getData('no_gutter');
    $no_gutter_inner = $_element->getData('no_gutter_inner');

    $block_container_class_arr[] = $container_outer_type_str;
    $block_inner_container_class_arr[] = $container_inner_type_str;

    if(!empty($no_gutter)) { $block_class_arr[] = "no-gutter"; }
    if(!empty($no_gutter_inner)) { $block_inner_container_class_arr[] = "no-gutter"; }

    // Carousel Options

    // General

    // Design Options

    // Generate class string
    // For the block
    if(!empty($block_class_arr))
        $block_class_str = join(" ", $block_class_arr);

    // Block container
    if(!empty($block_container_class_arr))
        $block_container_class_str = join(" ", $block_container_class_arr);

    // Inner block
    if(!empty($block_inner_class_arr))
        $block_inner_class_str = join(" ", $block_inner_class_arr);

    // Inner block container
    if(!empty($block_inner_container_class_arr))
        $block_inner_container_class_str = join(" ", $block_inner_container_class_arr);

    // Listings
    if(!empty($listings_class_arr))
        $listings_class_str = join(" ", $listings_class_arr);
?>

<?php if(!empty($block_active)): ?>

<div class="free-text">
<div class="container" style="margin-top:40px;
margin-bottom:40px;">
    <div class="row">
        <div class="col-md-12">
            <div class="user-content">
                <?php echo $block_content; ?>
            </div>
        </div>
    </div>
</div>

</div>
<?php endif; ?>