<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<div class="block account-nav">
    <div class="title">
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div>
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <?= $block->getChildHtml() ?>
                <li><a href="https://tracking.controlport.co.uk/e9ab6870/vieve-2/return/cda5cc"></a>Create a return </li>
            </ul>
        </nav>
    </div>
</div>
